# Generated by CodiumAI

from src.scripts.sonarcloud_metrics import rating_to_letter

import pytest


# Convert 1.0 to "A"
def test_convert_1_0_to_a():
    result = rating_to_letter(1.0)
    assert result == "A"


# Convert 0.3 to "A"
def test_convert_0_3_to_e():
    result = rating_to_letter(0.3)
    assert result == "A"


def test_convert_6_0_to_a():
    result = rating_to_letter(6.0)
    assert result == "E"
